export const LOOKS = [
  { name: 'terminal', brief: 'hacker terminal: monospace everything, blinking cursor, command-prompt layout, green/amber on black' },
  { name: 'neo-brutalist', brief: 'neo-brutalism: thick black borders, hard offset shadows, clashing flat colors, oversized type, asymmetric boxes' },
  { name: 'retro arcade', brief: '8-bit arcade cabinet: pixel font look, scanlines, chunky buttons, score HUD, limited bright palette' },
  { name: 'newspaper', brief: 'broadsheet newspaper front page: serif headlines, multi-column text, rules and datelines, sepia paper tones' },
  { name: 'synthwave', brief: '80s synthwave: neon gradients, perspective grid floor, glowing text, chrome headline' },
  { name: 'blueprint', brief: 'engineering blueprint: cyan grid paper, white line drawings, technical annotations and dimension marks' },
  { name: 'paper craft', brief: 'handmade paper collage: layered torn-paper shapes, soft shadows, sticker labels, warm pastels' },
  { name: 'swiss minimal', brief: 'Swiss editorial minimalism: strict grid, huge whitespace, one accent color, big grotesque numerals' },
  { name: 'dashboard', brief: 'dense ops dashboard: dark panels, status pills, sparklines, tiny uppercase labels, mission-control feel' },
  { name: 'comic book', brief: 'comic book: halftone dots, speech bubbles, bold outlines, action bursts, panel layout' },
  { name: 'vaporwave', brief: 'vaporwave: pastel pink/teal, marble-statue and sunset motifs in CSS, wide-tracking type, window chrome' },
  { name: 'receipt', brief: 'thermal receipt printout: narrow centered column, dotted dividers, monospace, itemized lines, barcode footer' },
  { name: 'botanical', brief: 'botanical field guide: cream paper, serif italics, specimen labels, muted greens, hand-drawn-feel borders' },
  { name: 'glassmorphism', brief: 'frosted glass cards over a vivid blurred gradient, soft light borders, rounded large radii' },
  { name: 'y2k', brief: 'Y2K web: bubbly gradients, chrome bevels, star and sparkle shapes, playful rounded sans, loud colors' },
  { name: 'mission control', brief: 'NASA-style mission control: countdown clocks, telemetry readouts, monochrome phosphor with red alerts' },
  { name: 'playful kids', brief: 'kids picture-book: huge rounded type, big friendly buttons, confetti colors, wobbly shapes' },
  { name: 'art deco', brief: 'art deco poster: gold on deep navy, symmetrical geometric ornaments, tall condensed headings' },
  { name: 'spreadsheet', brief: 'spreadsheet UI: cell grid, row/column headers, formula bar, the whole app lives inside the sheet' },
  { name: 'trading card', brief: 'collectible trading card: holographic foil, stat blocks, rarity badges, card-flip interactions' },
  { name: 'zine', brief: 'photocopied punk zine: black and white with one spot color, ransom-note lettering, tape, rotated elements' },
  { name: 'chat app', brief: 'messaging app: bubbles, avatars, typing indicators; the product experience is a conversation' },
  { name: 'retro OS', brief: 'classic desktop OS: draggable-looking windows, title bars, beveled buttons, taskbar, system dialogs' },
  { name: 'airport board', brief: 'split-flap departures board: rows of flipping characters, amber on black, gate and status columns' },
];

export const DEMOS = [
  'a small playable game with a score',
  'a random generator with a big button and shareable results',
  'a live simulation that animates on a canvas',
  'an interactive calculator or estimator with sliders',
  'a quiz that ends in a personalized verdict',
  'a data visualization you can poke and filter (use made-up data)',
  'a drag-and-drop or click-to-arrange puzzle',
  'a timer or countdown with escalating drama',
  'a fake-AI assistant with canned but funny replies',
  'a configurator that builds something and shows a live preview',
  'a leaderboard or voting widget with local state',
  'a step-by-step wizard with a dramatic finale',
  'a sound-free music or rhythm toy using keyboard/clicks',
  'a map or diagram you can explore by hovering and clicking',
  'a before/after or A/B comparison toy',
  'a text transformer that rewrites whatever you type',
];

export const DOMAINS = [
  'deploys and rollbacks', 'on-call and incidents', 'databases and Postgres', 'cron jobs and schedules',
  'logs and debugging', 'autoscaling and traffic spikes', 'preview environments', 'private networking',
  'cold starts and latency', 'build pipelines and CI', 'customer support tickets', 'pricing and invoices',
  'uptime and status pages', 'environment variables and secrets', 'infrastructure as code and Blueprints', 'git branches and pull requests',
  'code review', 'docs and onboarding', 'sales demos and customer calls', 'hiring and interviews',
  'all-hands and meetings', 'Slack and team chat', 'background workers and queues', 'AI agents and workflows',
  'pets and animals', 'cooking and recipes', 'weather', 'sports and fitness',
  'music and bands', 'travel and maps', 'gardening and plants', 'space and astronomy',
  'coffee and tea', 'board games', 'movies and TV', 'sleep and dreams',
  'weddings', 'spooky stories', 'mountains and camping', 'trivia and quizzes',
];
