projects:
  - name: makerdaymaker
    environments:
      - name: production
        services:
          - type: web
            name: makerdaymaker
            runtime: node
            plan: starter
            buildCommand: npm ci --include=dev && npm run build
            startCommand: npm start
            healthCheckPath: /api/config
            authentication:
              enabled: true
            envVars:
              - key: MAKER_DAY_LOCATION
                value: San Francisco
              - key: MAKER_DAY_YEAR
                value: "2027"
              - key: WORKFLOW_SLUG
                fromService:
                  type: workflow
                  name: makerdaymaker-workflow
                  property: slug
              - key: RENDER_API_KEY
                sync: false

          - type: workflow
            name: makerdaymaker-workflow
            runtime: node
            region: oregon
            buildCommand: npm ci --omit=dev
            startCommand: node workflow/index.js
            envVars:
              - fromGroup: rendervous-inference-keys
